# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableToChainReaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QTableWidgetItem, QLabel, QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 303, 373))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLevel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLevel.setMinimumSize(QtCore.QSize(30, 0))
        self.nameLevel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.nameLevel.setObjectName("nameLevel")
        self.gridLayout.addWidget(self.nameLevel, 2, 0, 1, 1)
        self.numLevel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLevel.sizePolicy().hasHeightForWidth())
        self.numLevel.setSizePolicy(sizePolicy)
        self.numLevel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.numLevel.setObjectName("numLevel")
        self.gridLayout.addWidget(self.numLevel, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)


        self.table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.table.setObjectName("tableView")
        self.table.setColumnCount(3)  # Устанавливаем три колонки
        self.table.setRowCount(3)  # и одну строку в таблице
        self.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.table.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        self.table.horizontalHeader().hide()
        self.table.verticalHeader().hide()

        self.table.setItem(0, 0, QTableWidgetItem("Text in column 1"))
        label = QLabel()
        label.setPixmap(QPixmap("../figures/draw-blue-circle.jpg"))
        self.table.setCellWidget(0, 1, label)


        self.verticalLayout.addWidget(self.table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameLevel.setText(_translate("MainWindow", "Level:"))
        self.numLevel.setText(_translate("MainWindow", "curLevel"))
        self.pushButton_2.setText(_translate("MainWindow", "Next"))
        self.pushButton.setText(_translate("MainWindow", "Prev"))



if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    mw = Ui_MainWindow()
    MainWindow = QtWidgets.QMainWindow()
    mw.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
